### ISSUE TITLE
create a database

### ISSUE THREAD

**Issue by francoPalacios** [francoPalacios/group-VJF#19]
### Epic Label

developer

### As a ...

developer

### I want to ...

create a create a backend model

### So that ...

I can store data for the app

**Comment by vathao777** [comment]
https://www.freesqldatabase.com/
email: vathoj86@gmail.com
Pw: @password1234
jdbc:mysql://sql3.freesqldatabase.com:3036/sql3683765
Your account number is: 870658

Your new database is now ready to use.

To connect to your database use these details;

Host: sql3.freesqldatabase.com
Database name: sql3683765
Database user: sql3683765
Database password: Jm9Umu7Ues
Port number: 3306
